Dim ret
Dim Filename
Dim objKSLData
Dim Status()
Redim Status(2000)
Set objKSLData = CreateObject("KSL450.clsKSLData")
ret = objKSLData.GetKSLFilename(Filename)
MsgBox Filename
ret = objKSLData.GetH81Status(0,Status)
MsgBox ret
MsgBox "Index 0 = " & Status(0)
MsgBox "Index 1 = " & Status(1)
MsgBox "Index 2 = " & Status(2)
MsgBox "Index 3 = " & Status(3)
MsgBox "Index 4 = " & Status(4)
MsgBox "Index 44 = " & Status(44)
MsgBox "Index 45 = " & Status(45)
MsgBox "Index 46 = " & Status(46)
MsgBox "Index 47 = " & Status(47)
MsgBox "Index 48 = " & Status(48)
MsgBox "Index 49 = " & Status(49)
MsgBox "Index 50 = " & Status(50)
ret = objKSLData.GetH81Status(1,Status)
MsgBox ret
MsgBox "Index 1.0 = " & Status(0)
MsgBox "Index 1.1 = " & Status(1)
MsgBox "Index 1.2 = " & Status(2)
MsgBox "Index 1.3 = " & Status(3)
MsgBox "Index 1.4 = " & Status(4)
MsgBox "Index 1.5 = " & Status(5)
MsgBox "Index 1.6 = " & Status(6)
MsgBox "Index 1.7 = " & Status(7)
MsgBox "Index 1.8 = " & Status(8)
MsgBox "Index 1.9 = " & Status(9)
MsgBox "Index 1.10 = " & Status(10)
MsgBox "Index 1.11 = " & Status(11)
ret = objKSLData.GetH81Status(2,Status)
MsgBox ret
MsgBox "Index 2.0 = " & Status(0)
MsgBox "Index 2.1 = " & Status(1)
MsgBox "Index 2.2 = " & Status(2)
MsgBox "Index 2.3 = " & Status(3)
MsgBox "Index 2.4 = " & Status(4)
MsgBox "Index 2.5 = " & Status(5)
MsgBox "Index 2.6 = " & Status(6)
MsgBox "Index 2.7 = " & Status(7)
MsgBox "Index 2.8 = " & Status(8)
MsgBox "Index 2.9 = " & Status(9)
MsgBox "Index 2.10 = " & Status(10)
MsgBox "Index 2.11 = " & Status(11)